# Generated by Django 6.0.1 on 2026-01-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='required_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='Not Provided', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='Not Provided', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Concert', 'Concert'), ('Private Function', 'Private Function'), ('College Events', 'College Events'), ('Group Dance', 'Group Dance')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('event', 'event_date')},
        ),
    ]
