# Generated by Django 6.0.1 on 2026-03-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
    ]
